### ISSUE TITLE
shift + enter does not work

### ISSUE THREAD

**Issue by caseyjenks** [kolybasov/ember-medium-editor#1]
It seems as if the onChange=(action (mut model.text))}} breaks shift + enter functionality for new lines. Any ideas?

**Comment by kolybasov** [comment]
@caseyjenks sorry for the late response. Could you provide more details please about your issue?
I tested <key>Enter</key> and <key>Shift</key>+<key>Enter</key> in the dummy map of this repo and it breaks line.
Are you sure [`disableReturn`](https://github.com/yabwe/medium-editor/blob/master/OPTIONS.md#disablereturn) option in your editor is `false`?

**Comment by caseyjenks** [comment]
Yes, disableReturn is false. The input receives the new line, but the cursor stays on the current line. Screencast here: https://cl.ly/0p0g0b0F2O27

**Comment by kolybasov** [comment]
@caseyjenks thanks for the screencast. There is [twiddle](https://ember-twiddle.com/3b8c667a6cccdf9655b583dea5ec87fa?openFiles=templates.application.hbs%2C), test please if it is works for you.
Be sure to check with your ember version and options.
If you will able to make it works as in your screencast – I can help with fix otherwise I just don't know what to fix.

**Comment by caseyjenks** [comment]
Ah ha, I found out why it works with your example but not mine. Give this a watch: https://cl.ly/1J413R151i2s

This would work fine, but then editing already persisted data becomes very hard. Any ideas?

**Comment by kolybasov** [comment]
@caseyjenks nice catch! Will try to fix it. Thanks! Also PR is always appreciated.
